# Amazon Electronics
**Dataset:** `McAuley-Lab/Amazon-Reviews-2023` (Electronics)

## Cài đặt thư viện

In [1]:
%%capture
!pip install datasets huggingface_hub pyarrow pandas fastparquet

## Cấu hình

In [2]:
import os
import warnings
import gc
warnings.filterwarnings('ignore')

import pandas as pd
import pyarrow as pa
from huggingface_hub import hf_hub_download, snapshot_download

CATEGORY   = "Electronics"
HF_REPO    = "McAuley-Lab/Amazon-Reviews-2023"
OUTPUT_DIR = "/kaggle/working/amazon_electronics"
os.makedirs(OUTPUT_DIR, exist_ok=True)

import psutil
ram_gb = psutil.virtual_memory().total / 1024**3
print(f"RAM khả dụng: {ram_gb:.0f} GB")

RAM khả dụng: 378 GB

## Tải Review Data

In [3]:
print(f"Đang tải Review data cho '{CATEGORY}' (Pandas)...")

review_local_path = hf_hub_download(
    repo_id=HF_REPO,
    repo_type="dataset",
    filename=f"raw/review_categories/{CATEGORY}.jsonl"
)

# Đọc file bằng Pandas
review_df = pd.read_json(review_local_path, lines=True)

print(f"Review records : {len(review_df):,}")
print(f"Columns        : {list(review_df.columns)}")
display(review_df.head(3))

Đang tải Review data cho 'Electronics' (Pandas)...

raw/review_categories/Electronics.jsonl:   0%|          | 0.00/22.6G [00:00<?, ?B/s]

Review records : 43,886,944
Columns        : ['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase']

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,3,Smells like gasoline! Going back!,First & most offensive: they reek of gasoline ...,[{'small_image_url': 'https://m.media-amazon.c...,B083NRGZMM,B083NRGZMM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2022-07-18 22:58:37.948,0,True
1,1,Didn’t work at all lenses loose/broken.,These didn’t work. Idk if they were damaged in...,[],B07N69T6TM,B07N69T6TM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2020-06-20 18:42:29.731,0,True
2,5,Excellent!,I love these. They even come with a carry case...,[],B01G8JO5F2,B01G8JO5F2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2018-04-07 09:23:37.534,0,True

## Tải Meta Data

In [4]:
print(f"Đang tải Meta data cho '{CATEGORY}' (Pandas)...")

meta_folder_path = snapshot_download(
    repo_id=HF_REPO,
    repo_type="dataset",
    allow_patterns=f"raw_meta_{CATEGORY}/*.parquet"
)

import glob
parquet_files = glob.glob(os.path.join(meta_folder_path, f"raw_meta_{CATEGORY}/*.parquet"))
meta_df = pd.concat([pd.read_parquet(f) for f in parquet_files], ignore_index=True)

print(f"Meta records   : {len(meta_df):,}")
print(f"Columns        : {list(meta_df.columns)}")
display(meta_df.head(3))

Đang tải Meta data cho 'Electronics' (Pandas)...

Fetching 10 files:   0%|          | 0/10 [00:16<?, ?it/s]

raw_meta_Electronics/full-00004-of-00010(…):   0%|          | 0.00/202M [00:00<?, ?B/s]

raw_meta_Electronics/full-00002-of-00010(…):   0%|          | 0.00/210M [00:00<?, ?B/s]

raw_meta_Electronics/full-00003-of-00010(…):   0%|          | 0.00/207M [00:00<?, ?B/s]

raw_meta_Electronics/full-00000-of-00010(…):   0%|          | 0.00/220M [00:00<?, ?B/s]

raw_meta_Electronics/full-00001-of-00010(…):   0%|          | 0.00/214M [00:00<?, ?B/s]

raw_meta_Electronics/full-00007-of-00010(…):   0%|          | 0.00/183M [00:00<?, ?B/s]

raw_meta_Electronics/full-00005-of-00010(…):   0%|          | 0.00/193M [00:00<?, ?B/s]

raw_meta_Electronics/full-00006-of-00010(…):   0%|          | 0.00/192M [00:00<?, ?B/s]

raw_meta_Electronics/full-00008-of-00010(…):   0%|          | 0.00/170M [00:00<?, ?B/s]

raw_meta_Electronics/full-00009-of-00010(…):   0%|          | 0.00/164M [00:00<?, ?B/s]

Meta records   : 1,610,012
Columns        : ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author']

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,The California Raisins Band includes Lead Sing...,4.8,10,[],[The California Raisins Band includes Lead Sin...,None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",The California Raisins,[],"{""Package Dimensions"": ""7.13 x 2.6 x 2.13 inch...",B003YTGP6C,NaN,NaN,NaN
1,Home Audio & Theater,Earbuds with Microphone Mic Noise Isolating Ea...,4.1,50,[],[],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Gsebr,"[Electronics, Headphones, Earbuds & Accessorie...","{""Manufacturer"": ""Gsebr"", ""Date First Availabl...",B088R7L6KS,NaN,NaN,NaN
2,Camera & Photo,Sony Alpha NEX-7 Digital Camera Body & E 18-55...,5.0,1,[],[],None,"{'hi_res': [None, None, None, None, None, None...","{'title': [], 'url': [], 'user_id': []}",Sony,"[Electronics, Camera & Photo, Digital Cameras]","{""Brand"": ""Sony"", ""Maximum Focal Length"": ""55 ...",B00DQW06GC,NaN,NaN,NaN

## Lọc dữ liệu

In [5]:
print("Đang lọc các cột cần thiết...")

review_cols = ['parent_asin', 'rating', 'timestamp', 'user_id']
review_df = review_df[review_cols]

print("Chỉ giữ lại các review có rating >= 4...")
review_df = review_df[review_df['rating'] >= 4]

meta_cols = ['title', 'rating_number', 'parent_asin', 'details']
meta_df = meta_df[meta_cols]

print("--- Review Data Info ---")
review_df.info()

print("\n--- Meta Data Info ---")
meta_df.info()

Đang lọc các cột cần thiết...
Chỉ giữ lại các review có rating >= 4...
--- Review Data Info ---
<class 'pandas.DataFrame'>
Index: 33387473 entries, 2 to 43886942
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   parent_asin  str
 1   rating       int64
 2   timestamp    datetime64[ms]
 3   user_id      str
dtypes: datetime64[ms](1), int64(1), str(2)
memory usage: 2.4 GB

--- Meta Data Info ---
<class 'pandas.DataFrame'>
RangeIndex: 1610012 entries, 0 to 1610011
Data columns (total 4 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   title          1610012 non-null  str
 1   rating_number  1610012 non-null  int64
 2   parent_asin    1610012 non-null  str
 3   details        1610012 non-null  str
dtypes: int64(1), str(3)
memory usage: 886.6 MB

In [6]:
before = len(review_df)
print(f"Trước dedup: {before:,} reviews")

# Với mỗi cặp (user_id, parent_asin), chỉ giữ review mới nhất theo timestamp
review_df = (
    review_df
    .sort_values("timestamp", ascending=False)
    .drop_duplicates(subset=["user_id", "parent_asin"], keep="first")
    .sort_values("timestamp")
    .reset_index(drop=True)
)

after = len(review_df)
print(f"Sau dedup : {after:,} reviews")
print(f"Đã xóa    : {before - after:,} duplicate reviews")

Trước dedup: 33,387,473 reviews
Sau dedup : 32,996,562 reviews
Đã xóa    : 390,911 duplicate reviews

## Lưu dữ liệu

In [7]:
import os

drive_path = "/kaggle/working/Data_Amazon_Electronics"
os.makedirs(drive_path, exist_ok=True)

print("Đang lưu Review Data vào ổ đĩa...")
review_df.to_parquet(f"{drive_path}/review_data.parquet", index=False)

print("\nĐang lưu Meta Data vào ổ đĩa...")
meta_df.to_parquet(f"{drive_path}/meta_data.parquet", index=False)

print(f"\nĐã lưu thành công dữ liệu vào: {drive_path}")

Đang lưu Review Data vào ổ đĩa...

Đang lưu Meta Data vào ổ đĩa...

Đã lưu thành công dữ liệu vào: /kaggle/working/Data_Amazon_Electronics

## Lọc dữ liệu K-core (k=5)

In [8]:
k = 5
iteration = 1
while True:
    start_len = len(review_df)
    
    # Lọc user có >= k đánh giá
    user_counts = review_df['user_id'].value_counts()
    valid_users = user_counts[user_counts >= k].index
    review_df = review_df[review_df['user_id'].isin(valid_users)]
    
    # Lọc item (parent_asin) có >= k đánh giá
    item_counts = review_df['parent_asin'].value_counts()
    valid_items = item_counts[item_counts >= k].index
    review_df = review_df[review_df['parent_asin'].isin(valid_items)]
    
    end_len = len(review_df)
    print(f"Lần lặp {iteration}: Số lượng review giảm từ {start_len:,} -> {end_len:,}")
    
    if start_len == end_len:
        print("Đã hội tụ!")
        break
    iteration += 1

print(f"\nSố lượng review cuối cùng sau khi lọc 5-core: {len(review_df):,}")
print(f"Số lượng Users: {review_df['user_id'].nunique():,}")
print(f"Số lượng Items: {review_df['parent_asin'].nunique():,}")

print("\nĐang cập nhật lại Meta Data...")
valid_items_final = review_df['parent_asin'].unique()
meta_df = meta_df[meta_df['parent_asin'].isin(valid_items_final)].reset_index(drop=True)
print(f"Số lượng Meta records cuối cùng: {len(meta_df):,}")

Lần lặp 1: Số lượng review giảm từ 32,996,562 -> 11,291,817
Lần lặp 2: Số lượng review giảm từ 11,291,817 -> 10,596,366
Lần lặp 3: Số lượng review giảm từ 10,596,366 -> 10,554,858
Lần lặp 4: Số lượng review giảm từ 10,554,858 -> 10,552,057
Lần lặp 5: Số lượng review giảm từ 10,552,057 -> 10,551,881
Lần lặp 6: Số lượng review giảm từ 10,551,881 -> 10,551,877
Lần lặp 7: Số lượng review giảm từ 10,551,877 -> 10,551,877
Đã hội tụ!

Số lượng review cuối cùng sau khi lọc 5-core: 10,551,877
Số lượng Users: 1,145,516
Số lượng Items: 284,008

Đang cập nhật lại Meta Data...
Số lượng Meta records cuối cùng: 284,008

In [9]:
print("Đang lưu Review Data vào ổ đĩa...")
review_df.to_parquet(f"{drive_path}/review_data_5_core.parquet", index=False)

print("\nĐang lưu Meta Data vào ổ đĩa...")
meta_df.to_parquet(f"{drive_path}/meta_data_5_core.parquet", index=False)

print(f"\nĐã lưu thành công dữ liệu vào: {drive_path}")

Đang lưu Review Data vào ổ đĩa...

Đang lưu Meta Data vào ổ đĩa...

Đã lưu thành công dữ liệu vào: /kaggle/working/Data_Amazon_Electronics